routes/web.php
<?php

use Illuminate\Http\Request;


Route::get('/', 'UserController@index')->name('home');
Route::get('/signin', 'UserController@signin')->name('signin');
Route::get('search','PropertyController@search')->name('search');
Route::get('/properties', 'PropertyController@index')->name('properties');
Route::get('/property/{id}/{name}', 'PropertyController@detail')->name('detail');
Route::post('/deal-submited', 'PropertyController@ajaxDeal')->name('ajaxDeal');
Route::get('/agreement', 'PropertyController@agreement')->name('agreement');
Route::post('/agreement', 'PropertyController@agreementPost')->name('agreement');


Route::group(['middleware' => ['auth']], function () {
    Route::get('/submit-property', 'PropertyController@submitProperty')->name('submit.property');
    Route::post('/submit-property', 'PropertyController@submitPropertyPost')->name('submit.property');
    Route::get('/my-profile', 'ProfileController@myProfile')->name('myProfile');
    Route::post('/my-profile', 'ProfileController@submitProfile')->name('submitProfile');
    Route::get('/change-password','HomeController@showChangePasswordForm')->name('changePasswordForm');
    Route::post('/changePassword','HomeController@changePassword')->name('changePassword');
    Route::get('/my-property','PropertyController@myproperty')->name('myProperty');
    Route::get('/delete-property/{id}','PropertyController@removeProperty')->name('removeProperty');
    Route::get('/edit-property/{id}','PropertyController@editProperty')->name('editProperty');
    Route::post('/edit-property', 'PropertyController@editPropertyPost')->name('submit.editPropertyPost');
    
});
Auth::routes();
//Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix' =>'admin','namespace'=>'Admin','as' => 'admin.'], function () {

    Route::get('/', function () {
        return redirect(route("admin.login"));
    });
    
    //Login Routes...
    Route::get('login','Auth\LoginController@showLoginForm')->name('login');
    Route::post('login','Auth\LoginController@login')->name('login');
    Route::post('logout','Auth\LoginController@logout')->name('logout');

    // Registration Routes...
    Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
    Route::post('register', 'Auth\RegisterController@register')->name('register');

    Route::group(['middleware' => ['auth:admin']], function () {
        Route::get('/home', 'HomeController@index')->name('home');
        Route::get('/agent', 'AgentController@index')->name('agent');
        Route::get('/ajax_get_agent', 'AgentController@ajax_get_agent')->name('ajax_get_agent');
        Route::get('agent/detail/{id}', 'AgentController@detail')->name('detail');
        Route::get('agent/detail/{id}/approval/yes', 'AgentController@agent_approvl_yes')->name('agent_approvl_yes');
        Route::get('agent/detail/{id}/suspend/yes', 'AgentController@agent_suspend_yes');
        Route::get('agent/detail/{id}/suspend/no', 'AgentController@agent_suspend_no');
        Route::get('agent/detail/{id}/power', 'AgentController@power')->name('power');
        Route::get('agent/detail/{id}/power/manager', 'PowerController@power_manager')->name('power_manager');
        Route::get('agent/detail/{id}/power/assistant', 'PowerController@power_assist')->name('power_assist');
        Route::get('agent/detail/{id}/power/remove', 'PowerController@power_remove')->name('power_remove');
        
        Route::get('featured', 'PropertyController@featured')->name('featured');
        Route::get('ajax-featured', 'PropertyController@ajaxFeatured')->name('ajaxFeatured');
        Route::get('featured/{id}/{mark}', 'PropertyController@mark_as_featured')->name('mark_as');
        Route::get('agreement', 'PropertyController@agreement')->name('agreement');
        Route::get('ajax-agreement', 'PropertyController@ajaxAgreement')->name('ajaxAgreement');
        Route::get('agreement/download/{id}', 'PropertyController@agreementDownload')->name('agreement.download');

        
        
    });
});

Route::get('email_verify',function (){
    return view('agent.email.emailverification');
})->name('email_verify');
Route::post('email_verify','Agent\EmailController@email_verifyPost')->name('emailverificationPost');
Route::get('resend_email_code','Agent\EmailController@resend_email_code')->name('resend.email.code');
Route::get('acount_approval',function (){
    return view('agent.restrictions.approval');
})->name('acount_approval');
Route::get('acount_suspend',function (){
    return view('agent.restrictions.suspend');
})->name('acount_suspend');



Route::get('email_tamplate','Agent\EmailController@email_tamplate');
Route::group(['prefix' =>'agent','namespace'=>'Agent','as' => 'agent.','middleware' => ['agent:agent']], function () {

    Route::get('/', function () {
        return redirect(route("agent.login"));
    });
    
    
    
    //Login Routes...
    Route::get('login','Auth\LoginController@showLoginForm')->name('login');
    Route::post('login','Auth\LoginController@login')->name('login');
    Route::post('logout','Auth\LoginController@logout')->name('logout');

    // Registration Routes...
    Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
    Route::post('register', 'Auth\RegisterController@register')->name('register');
    Route::group(['middleware' => ['auth:agent']], function () {
        Route::get('/home', 'HomeController@index')->name('home');
        Route::get('/add_property', 'PropertyController@add_property')->name('add.property');
        Route::post('/add_property', 'PropertyController@add_propertyPost')->name('property.Post');
        Route::get('/myproperty', 'PropertyController@myproperty')->name('my.property');
        Route::get('/ajaxmypropertydata', 'PropertyController@ajaxmypropertydata')->name('ajaxmypropertydata');
        Route::get('/viewproperty/{id}', 'PropertyController@viewproperty')->name('viewproperty');
        Route::get('/property/new-request', 'PropertyController@newRequest')->name('property.request');
        Route::get('/property', 'PropertyController@allProperty')->name('property.all');
        Route::get('/property/all-property', 'PropertyController@ajaxallProperty')->name('ajaxallProperty');
        
        
        Route::get('/property/new-property-request', 'PropertyController@ajaxNewPropertyRequest')->name('ajaxNewPropertyRequest');
        Route::get('/property/new-deals', 'DealsController@newDeals')->name('new.deals');
        Route::get('/property/ajax-new-deals', 'DealsController@ajaxNewDeals')->name('ajaxNewDeals');
        Route::get('/deal-accept/{id}', 'DealsController@acceptDeal');
        Route::get('/deal-reject/{id}', 'DealsController@rejectDeal');
        Route::get('/deal-complete/{id}', 'DealsController@completeDeal');
        Route::get('/deal-delete/{id}', 'DealsController@deleteDeal');
        Route::get('/accept-property/{id}', 'PropertyController@acceptProperty')->name('acceptProperty');
        Route::get('/delete-property/{id}', 'PropertyController@deleteProperty')->name('deleteProperty');
        Route::get('/delete-my-property/{id}', 'PropertyController@deleteMyProperty')->name('deleteMyProperty');
        Route::get('/ajax-my-property', 'PropertyController@ajaxMyProperty')->name('ajaxMyProperty');
        Route::get('/my-all-deals', 'DealsController@myAllDeals')->name('my.all.property');
        Route::get('/ajax-my-all-deals', 'DealsController@ajaxMyAllDeals')->name('ajaxMyAllDeals');
        
    });
});

app/Http/Controllers/Admin/AgentController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use Closure;
use Auth;
use App\Model\Agent;
use DataTables;
use Redirect;
use Mail;
class AgentController extends Controller
{
    

    public function index()
    {
        return view('admin.agent.index');
    }
    public function ajax_get_agent(Request $request)
    {   
        $agent = Agent::get();
        
        return Datatables::of($agent)->make(true);
    }
    public function detail($id)
    {   
        $agent = Agent::where('id',$id)->first();
        
        return view('admin.agent.detail',compact('agent'));
    }
    public function agent_approvl_yes($id)
    {   
        $agent = Agent::where('id',$id)->first();
        $agent->approval=1;
        $agent->save();
        Mail::send('agent.email.approval_tamplate', ['agent' => $agent], function ($message)use ($agent)
        {   
                $message->from('bbclands@gmail.com', 'BBClands Team');
                $message->to($agent->email);
        });
        return Redirect::back();
    }
    public function agent_suspend_yes($id)
    {   
        $agent = Agent::where('id',$id)->first();
        $agent->suspend=1;
        $agent->save();
        /* Mail::send('agent.email.approval_tamplate', ['agent' => $agent], function ($message)use ($agent)
        {   
                $message->from('bbclands@gmail.com', 'BBClands Team');
                $message->to($agent->email);
        }); */
        return Redirect::back();
    }
    public function agent_suspend_no($id)
    {   
        $agent = Agent::where('id',$id)->first();
        $agent->suspend=0;
        $agent->save();
        /* Mail::send('agent.email.approval_tamplate', ['agent' => $agent], function ($message)use ($agent)
        {   
                $message->from('bbclands@gmail.com', 'BBClands Team');
                $message->to($agent->email);
        }); */
        return Redirect::back();
    }
    public function power($id)
    {   
        return view('admin.agent.power',compact('id'));
    }

}

app/Http/Controllers/Agent/Controller.php
<?php

namespace App\Http\Controllers\Agent;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/Agent/DealsController.php
<?php 
namespace App\Http\Controllers\Agent;

use Illuminate\Http\Request;
use Closure;
use Auth;
use App\Model\Property;
use Illuminate\Support\Facades\Input;
use DataTables;
use App\Model\Deals;
class DealsController extends Controller
{
    public function newDeals(Request $request)
    {   
        if(!Auth::guard('agent')->user()->power){
            abort(404);
         }
        return view('agent.deals.new_deals');
    }
    public function ajaxNewDeals(Request $request)
    {   
        $deals = Deals::with('property')->where('status', 'new')->where('delete', 0);
        return DataTables::of($deals)->make(true);
    }
    public function acceptDeal($id,Request $request)
    {   
        $deals = Deals::where('id', $id)->first();
        $deals->status="progress";
        $deals->save();
        return redirect()->back();
    }
    /* public function rejectDeal($id,Request $request)
    {   
        $deals = Deals::where('id', $id)->first();
        $deals->status="progress";
        $deals->save();
        return redirect()->back();
    } */
    public function completeDeal($id,Request $request)
    {   
        $deals = Deals::where('id', $id)->first();
        $deals->status="done";
        $deals->save();
        return redirect()->back();
    }
    public function deleteDeal($id,Request $request)
    {   
        $deals = Deals::where('id', $id)->first();
        $deals->delete=1;
        $deals->save();
        return redirect()->back();
    }
    public function myAllDeals(Request $request)
    {   
        return view('agent.deals.my_deals');
    }
    public function ajaxMyAllDeals(Request $request)
    {   
        $deals = Deals::with('property')->where('delete', 0);
        return DataTables::of($deals)->make(true);
    }
    
}

app/Http/Controllers/Agent/EmailController.php
<?php 
namespace App\Http\Controllers\Agent;

use Illuminate\Http\Request;
use Closure;
use Auth;
use App\Model\Agent;
use Illuminate\Support\Facades\Input;
use DataTables;
use Redirect;
use Mail;
class EmailController extends Controller
{
    protected function email_verifyPost(Request $request){
        
        $data = $request->all();
        $user =Agent::where('id', Auth::guard("agent")->user()->id)->first();
        if($user->email_verify_code==$data['email_code']){
            $user->email_verified=1;
            $user->save();
            return redirect("agent/home");
        }
        else 
        {
            $request->session()->flash('error', 'Wrong Verificaton Code'); 
            return view('agent.email.emailverification');
        }
        
    }
    protected function resend_email_code(Request $request){
        $email_code = mt_rand(100000,999999);
        $agent =Agent::where('id', Auth::guard("agent")->user()->id)->first();
        $agent->email_verify_code = $email_code;
        $agent->save();
        /* Mail::raw('Email verification code is '.$email_code, function ($message)use ($agent) {
            $message->to($agent->email);
         }); */

            Mail::send('agent.email.emailverify_tamplate', ['agent' => $agent,'email_code'=>$email_code], function ($message)use ($agent)
            {   
                $message->from('bbclands@gmail.com', 'BBClands Team');
                $message->to($agent->email);
            });
          $request->session()->flash('error', 'Email Has been sent again. Please check inbox');
          return Redirect::back(); 
    }
    protected function email_tamplate(Request $request){
        
        return view('agent.email.emailverify_tamplate');
    
    }
}

app/Http/Controllers/Agent/HomeController.php
<?php

namespace App\Http\Controllers\Agent;

use Illuminate\Http\Request;
use Closure;
use Auth;
use App\Http\Controllers\Controller;
class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    protected $guard = 'agent';
    public function __construct()
    {
        
        $this->middleware('agent:agent', ['except' => 'logout'])->except('logout');
        /* if(!Auth::guard('agent')->check()){
            return redirect('/agent/login');
        }
        if(Auth::guard('agent')->check()){
            return redirect('/agent/home');
        } */
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        /* if(!Auth::guard('agent')->check()){
            return redirect('/agent/login');
        } */
        return view('agent.dashboard.index');
    }
    protected function guard() {
        return Auth::guard('agent:agent');
    }
}

resources/views/admin/agent/detail.blade.php
@extends('admin.layouts.app')

@section('content')
<div class="right_col" role="main">
<div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>{{$agent->name}} <small> {{$agent->email}}</small></h2>
                    
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                    <br />
                    <div>
                    <div class="row">
                        <div class="col-sm-3" >
                            <p>Power: </p>
                        </div>
                        <div class="col-sm-6" >
                            <p>
                                @if($agent->power=="manager")
                                        Manager
                                @endif
                                @if(!$agent->power)
                                        Nothing
                                @endif
                            </p>
                        </div>
                        <div class="col-sm-3" >
                        <a href="{{route('admin.power',$agent->id)}}"class="btn btn-info btn-md">Action</a>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-3" >
                            <p>Email Verified: </p>
                        </div>
                        <div class="col-sm-9" >
                            <p>
                                @if($agent->email_verified==1)
                                        Verified
                                @endif
                                @if($agent->email_verified==0)
                                        Email Not Verified
                                @endif
                            </p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-3" >
                            <p>Registered At: </p>
                        </div>
                        <div class="col-sm-9" >
                            <p>
                              {{$agent->created_at}}
                            </p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-3" >
                            <p>Approved: </p>
                        </div>
                        <div class="col-sm-6" >
                            <p>
                            @if($agent->approval==1)
                                        Approved
                            @endif
                            @if($agent->approval==0)
                                        Not Approved
                            @endif
                            </p>
                        </div>
                        <div class="col-sm-3" >
                        @if($agent->approval==1)
                        <a  class="btn btn-danger btn-md">Reject</a>
                            @endif
                            @if($agent->approval==0)
                                <a href="/admin/agent/detail/{{$agent->id}}/approval/yes" class="btn btn-primary btn-md">Accept</a>
                            @endif
                        
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-3" >
                            <p>Susspended Status: </p>
                        </div>
                        <div class="col-sm-6" >
                            <p>
                            @if($agent->suspend==1)
                                        No
                            @endif
                            @if($agent->suspend==0)
                                        Yes
                            @endif
                            </p>
                        </div>
                        <div class="col-sm-3" >
                        @if($agent->suspend==1)
                            <a href="/admin/agent/detail/{{$agent->id}}/suspend/no" class="btn btn-primary btn-md">Unblock</a>
                            @endif
                            @if($agent->suspend==0)
                            <a href="/admin/agent/detail/{{$agent->id}}/suspend/yes" class="btn btn-danger btn-md">Block</a>
                            @endif
                        
                        </div>
                    </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            </div>
@endsection

resources/views/admin/agent/index.blade.php
@extends('admin.layouts.app')

@section('content')
<div class="right_col" role="main">
         
<div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Agents <small></small></h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      
                    </ul>
                    <div class="clearfix"></div>
                  </div>

                  <div class="x_content">

                    <!-- <p>Add class <code>bulk_action</code> to table for bulk actions options on row select</p> -->

                    <div class="table-responsive">
                      <table id="agent_table" class="table table-striped jambo_table bulk_action">
                        <thead>
                          <tr class="headings">
                            
                            <th class="column-title"># </th>
                            <th class="column-title">Name </th>
                            <th class="column-title">Email </th>
                            <th class="column-title">Power </th>
                          </tr>
                        </thead>

                      </table>
                    </div>
@endsection
@section('script')

<script type="text/javascript">
 $(document).ready(function () {
    
    $('#agent_table').DataTable({
   
        processing: true,
        serverSide: true,
        ajax:{ 
            "url":  '{{url('admin/ajax_get_agent')}}' ,
            data: {
            'csrf_token':$('meta[name=csrf_token]').attr("content")
            }
        },
        
        columns: [
            {
                
                "mData": null,
                "bSortable": false,
                //name:"settlement.id",
               "mRender": function (data) { 
                   return `
                        <a style="color:blue"  title="View Agent" href=/admin/agent/detail/${data.id}>${data.id}</a>
                    `; 
                }
            },
           { data: 'name', name: 'name' },  
          { data: 'email', name: 'email' },
          {
                
                "mData": null,
                "bSortable": false,
                //name:"settlement.id",
               "mRender": function (data) { 
                   if(data.power=="manager"){
                    return `
                        <span class="label label-info">Manager</span>
                    `; 
                   }
                   if(!data.power){
                    return `<span class="label label-info">None</span>
                     `;  }
                    return `
                        <span class="label label-info">${data.power}</span>
                    `; 
                   }
                   
                }
            
        ]
    });
});
</script>

@endsection

resources/views/admin/agent/power.blade.php
@extends('admin.layouts.app')

@section('content')
<div class="right_col" role="main">
         
<div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Grand Powers <small></small></h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      
                    </ul>
                    <div class="clearfix"></div>
                  </div>

                  <div class="x_content">

                    <div class="table-responsive">
                      <table id="agent_table" class="table">
                        <thead>
                          <tr class="headings">
                            
                            <th class="column-title">Powers Name </th>
                            <th class="column-title">Can Do </th>
                            <th class="column-title"> </th>
                          </tr>
                        </thead>
                        <tbody>
                          <tr>
                            <td>Manager</td>
                            <td>Delete Property, Set Perority , Can  view All types of deals</td>
                            <td><a href="{{route('admin.power_manager',$id)}}" class="btn btn-success">Set</a></td>
                          </tr>
                          <tr>
                            <td>Assistant</td>
                            <td>Can  view All types of deals </td>
                            <td><a href="{{route('admin.power_assist',$id)}}"  class="btn btn-success">Set</a></td>
                          </tr>
                        </tbody>
                      </table>
                      <a href="{{route('admin.power_remove',$id)}}"  class="btn btn-success">Remove All Power</a>
                    </div>

@endsection