routes/web.php
<?php

use Illuminate\Http\Request;


Route::get('/', 'UserController@index')->name('home');
Route::get('/signin', 'UserController@signin')->name('signin');
Route::get('search','PropertyController@search')->name('search');
Route::get('/properties', 'PropertyController@index')->name('properties');
Route::get('/property/{id}/{name}', 'PropertyController@detail')->name('detail');
Route::post('/deal-submited', 'PropertyController@ajaxDeal')->name('ajaxDeal');
Route::get('/agreement', 'PropertyController@agreement')->name('agreement');
Route::post('/agreement', 'PropertyController@agreementPost')->name('agreement');


Route::group(['middleware' => ['auth']], function () {
    Route::get('/submit-property', 'PropertyController@submitProperty')->name('submit.property');
    Route::post('/submit-property', 'PropertyController@submitPropertyPost')->name('submit.property');
    Route::get('/my-profile', 'ProfileController@myProfile')->name('myProfile');
    Route::post('/my-profile', 'ProfileController@submitProfile')->name('submitProfile');
    Route::get('/change-password','HomeController@showChangePasswordForm')->name('changePasswordForm');
    Route::post('/changePassword','HomeController@changePassword')->name('changePassword');
    Route::get('/my-property','PropertyController@myproperty')->name('myProperty');
    Route::get('/delete-property/{id}','PropertyController@removeProperty')->name('removeProperty');
    Route::get('/edit-property/{id}','PropertyController@editProperty')->name('editProperty');
    Route::post('/edit-property', 'PropertyController@editPropertyPost')->name('submit.editPropertyPost');
    
});
Auth::routes();
//Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix' =>'admin','namespace'=>'Admin','as' => 'admin.'], function () {

    Route::get('/', function () {
        return redirect(route("admin.login"));
    });
    
    //Login Routes...
    Route::get('login','Auth\LoginController@showLoginForm')->name('login');
    Route::post('login','Auth\LoginController@login')->name('login');
    Route::post('logout','Auth\LoginController@logout')->name('logout');

    // Registration Routes...
    Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
    Route::post('register', 'Auth\RegisterController@register')->name('register');

    Route::group(['middleware' => ['auth:admin']], function () {
        Route::get('/home', 'HomeController@index')->name('home');
        Route::get('/agent', 'AgentController@index')->name('agent');
        Route::get('/ajax_get_agent', 'AgentController@ajax_get_agent')->name('ajax_get_agent');
        Route::get('agent/detail/{id}', 'AgentController@detail')->name('detail');
        Route::get('agent/detail/{id}/approval/yes', 'AgentController@agent_approvl_yes')->name('agent_approvl_yes');
        Route::get('agent/detail/{id}/suspend/yes', 'AgentController@agent_suspend_yes');
        Route::get('agent/detail/{id}/suspend/no', 'AgentController@agent_suspend_no');
        Route::get('agent/detail/{id}/power', 'AgentController@power')->name('power');
        Route::get('agent/detail/{id}/power/manager', 'PowerController@power_manager')->name('power_manager');
        Route::get('agent/detail/{id}/power/assistant', 'PowerController@power_assist')->name('power_assist');
        Route::get('agent/detail/{id}/power/remove', 'PowerController@power_remove')->name('power_remove');
        
        Route::get('featured', 'PropertyController@featured')->name('featured');
        Route::get('ajax-featured', 'PropertyController@ajaxFeatured')->name('ajaxFeatured');
        Route::get('featured/{id}/{mark}', 'PropertyController@mark_as_featured')->name('mark_as');
        Route::get('agreement', 'PropertyController@agreement')->name('agreement');
        Route::get('ajax-agreement', 'PropertyController@ajaxAgreement')->name('ajaxAgreement');
        Route::get('agreement/download/{id}', 'PropertyController@agreementDownload')->name('agreement.download');

        
        
    });
});

Route::get('email_verify',function (){
    return view('agent.email.emailverification');
})->name('email_verify');
Route::post('email_verify','Agent\EmailController@email_verifyPost')->name('emailverificationPost');
Route::get('resend_email_code','Agent\EmailController@resend_email_code')->name('resend.email.code');
Route::get('acount_approval',function (){
    return view('agent.restrictions.approval');
})->name('acount_approval');
Route::get('acount_suspend',function (){
    return view('agent.restrictions.suspend');
})->name('acount_suspend');



Route::get('email_tamplate','Agent\EmailController@email_tamplate');
Route::group(['prefix' =>'agent','namespace'=>'Agent','as' => 'agent.','middleware' => ['agent:agent']], function () {

    Route::get('/', function () {
        return redirect(route("agent.login"));
    });
    
    
    
    //Login Routes...
    Route::get('login','Auth\LoginController@showLoginForm')->name('login');
    Route::post('login','Auth\LoginController@login')->name('login');
    Route::post('logout','Auth\LoginController@logout')->name('logout');

    // Registration Routes...
    Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
    Route::post('register', 'Auth\RegisterController@register')->name('register');
    Route::group(['middleware' => ['auth:agent']], function () {
        Route::get('/home', 'HomeController@index')->name('home');
        Route::get('/add_property', 'PropertyController@add_property')->name('add.property');
        Route::post('/add_property', 'PropertyController@add_propertyPost')->name('property.Post');
        Route::get('/myproperty', 'PropertyController@myproperty')->name('my.property');
        Route::get('/ajaxmypropertydata', 'PropertyController@ajaxmypropertydata')->name('ajaxmypropertydata');
        Route::get('/viewproperty/{id}', 'PropertyController@viewproperty')->name('viewproperty');
        Route::get('/property/new-request', 'PropertyController@newRequest')->name('property.request');
        Route::get('/property', 'PropertyController@allProperty')->name('property.all');
        Route::get('/property/all-property', 'PropertyController@ajaxallProperty')->name('ajaxallProperty');
        
        
        Route::get('/property/new-property-request', 'PropertyController@ajaxNewPropertyRequest')->name('ajaxNewPropertyRequest');
        Route::get('/property/new-deals', 'DealsController@newDeals')->name('new.deals');
        Route::get('/property/ajax-new-deals', 'DealsController@ajaxNewDeals')->name('ajaxNewDeals');
        Route::get('/deal-accept/{id}', 'DealsController@acceptDeal');
        Route::get('/deal-reject/{id}', 'DealsController@rejectDeal');
        Route::get('/deal-complete/{id}', 'DealsController@completeDeal');
        Route::get('/deal-delete/{id}', 'DealsController@deleteDeal');
        Route::get('/accept-property/{id}', 'PropertyController@acceptProperty')->name('acceptProperty');
        Route::get('/delete-property/{id}', 'PropertyController@deleteProperty')->name('deleteProperty');
        Route::get('/delete-my-property/{id}', 'PropertyController@deleteMyProperty')->name('deleteMyProperty');
        Route::get('/ajax-my-property', 'PropertyController@ajaxMyProperty')->name('ajaxMyProperty');
        Route::get('/my-all-deals', 'DealsController@myAllDeals')->name('my.all.property');
        Route::get('/ajax-my-all-deals', 'DealsController@ajaxMyAllDeals')->name('ajaxMyAllDeals');
        
    });
});

resources/views/admin/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title> :: BBCLands :: </title>
   
    

    <!-- Bootstrap -->
    <link href="{{ asset('gentelella/vendors/bootstrap/dist/css/bootstrap.min.css') }}" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{{ asset('gentelella/vendors/font-awesome/css/font-awesome.min.css') }}" rel="stylesheet">
    <!-- NProgress -->
    <link href="{{ asset('gentelella/vendors/nprogress/nprogress.css') }}" rel="stylesheet">
    <!-- iCheck -->
    <link href="{{ asset('gentelella/vendors/iCheck/skins/flat/green.css') }}" rel="stylesheet">
    <!-- Datatables -->
    <link href="{{ asset('gentelella/vendors/datatables.net-bs/css/dataTables.bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ asset('gentelella/vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ asset('gentelella/vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ asset('gentelella/vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ asset('gentelella/vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css') }}" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="{{ asset('gentelella/build/css/custom.min.css') }}" rel="stylesheet">

    <!-- bootstrap-progressbar -->
    <link href="{{ asset('gentelella/vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css') }}" rel="stylesheet">
    <!-- JQVMap -->
    <link href="{{ asset('gentelella/vendors/jqvmap/dist/jqvmap.min.css') }}" rel="stylesheet">
    <!-- bootstrap-daterangepicker -->
    <link href="{{ asset('gentelella/vendors/bootstrap-daterangepicker/daterangepicker.css') }}" rel="stylesheet">
    <link href="{{ asset('css/custom-app.css') }}" rel="stylesheet">
    @yield("css")
</head>
<body class="nav-md">
<div class="container body">
    <div class="main_container">
        @if (Auth::guard('admin')->check())
            <div class="col-md-3 left_col">
                <div class="left_col scroll-view">
                    <div class="navbar nav_title" style="border: 0;">
                    <a class="navbar-brand" href="{{ route('admin.home') }}">
                    <span></span>
                    <span><img height="40px" width="190px" src='{{asset("/img/logo.png")}}' /></span>
                    </a>
                    </div>

                    <div class="clearfix"></div>

                    <!-- menu profile quick info -->
                    <div class="profile clearfix">
                        <div class="profile_pic">
                            <!-- <img src="images/img.jpg" alt="..." class="img-circle profile_img"> -->
                        </div>
                        <div class="profile_info">
                            <span>Welcome,</span>
                            
                            <h2>{{ Auth::guard('admin')->user()->name }}</h2>
                            
                        </div>
                    </div>
                    <!-- /menu profile quick info -->

                    <br />

                    <!-- sidebar menu -->
                    <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
                        <div class="menu_section">
                            <h3>General</h3>
                            <ul class="nav side-menu">
                           <li><a href="#"><i class="fa fa-home"></i> Dashboard </a></li>
                           <li><a href="{{route('admin.agent')}}"><i class="fa fa-home"></i> Agents </a></li>
                           <li><a href="{{route('admin.featured')}}"><i class="fa fa-home"></i> Featured </a></li>
                           <li><a href="#"><i class="fa fa-home"></i> Deals </a></li>
                           <li><a href="#"><i class="fa fa-home"></i> Users </a></li>
                           <li><a href="{{route('admin.agreement')}}"><i class="fa fa-home"></i> Agreement </a></li>
                           
                        </div>


                    </div>

                </div>
            </div>
            <div class="top_nav">
                <div class="nav_menu" style="margin-bottom:-1px !important;">
                    <nav>
                        <div class="nav toggle">
                            <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                        </div>

                        <ul class="nav navbar-nav navbar-right">
                        @if (!Auth::guard('admin')->check())
                            <li><a href="{{ route('login') }}">Login</a></li>
                         <!--    <li><a href="{{ route('register') }}">Register</a></li> -->
                        @else
                            <li class="">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true" v-pre>
                                        {{ Auth::guard('admin')->user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu">
                                        <li>
                                            <a href="{{ route('admin.logout') }}"
                                                onclick="event.preventDefault();
                                                        document.getElementById('logout-form').submit();">
                                                Logout
                                            </a>

                                            <form id="logout-form" action="{{ route('admin.logout') }}" method="POST" style="display: none;">
                                                {{ csrf_field() }}
                                            </form>
                                        </li>
                                </ul>
                            </li>
                        @endif
                           
                        </ul>
                    </nav>
                </div>
                
            </div>
            @endif
        <div class="container">
        <div class="row">
            <div class="col-md-10" style=" float:  right;">
            @if($msg = session("message"))
            <div  class="alert alert-success alert-dismissible fade in" role="alert">
                   
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span>
                    </button>
                    <strong> {{$msg}} </strong>
                  </div>
               
            @endif  
            @if($error = session("error"))
            <div  class="alert alert-danger alert-dismissible fade in" role="alert">
                   
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span>
                    </button>
                    <strong> {{$error}} </strong>
                  </div>
                 
            @endif 
            </div>
        </div>
          
        </div>
        

            
    </div>

    @yield('content')
        

            <!-- jQuery -->
    <script src="{{ asset('gentelella/vendors/jquery/dist/jquery.min.js') }}"></script>
    <!-- Bootstrap -->
    <!-- <script src="{{ asset('gentelella/vendors/bootstrap/dist/js/bootstrap.min.js') }}"></script> -->
    <!-- FastClick -->
    <script src="{{ asset('gentelella/vendors/fastclick/lib/fastclick.js') }}"></script>
    <!-- NProgress -->
    <script src="{{ asset('gentelella/vendors/nprogress/nprogress.js') }}"></script>
    <!-- iCheck -->
    <script src="{{ asset('gentelella/vendors/iCheck/icheck.min.js') }}"></script>
    <!-- Datatables -->
    <script src="{{ asset('gentelella/vendors/datatables.net/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('gentelella/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>
    <script src="{{ asset('gentelella/vendors/datatables.net-buttons/js/dataTables.buttons.min.js') }}"></script>
    <script src="{{ asset('gentelella/vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js') }}"></script>
    <script src="{{ asset('gentelella/vendors/datatables.net-buttons/js/buttons.flash.min.js') }}"></script>
    <script src="{{ asset('gentelella/vendors/datatables.net-buttons/js/buttons.html5.min.js') }}"></script>
    <script src="{{ asset('gentelella/vendors/datatables.net-buttons/js/buttons.print.min.js') }}"></script>
    <script src="{{ asset('gentelella/vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js') }}"></script>
    <script src="{{ asset('gentelella/vendors/datatables.net-keytable/js/dataTables.keyTable.min.js') }}"></script>
    <script src="{{ asset('gentelella/vendors/datatables.net-responsive/js/dataTables.responsive.min.js') }}"></script>
    <script src="{{ asset('gentelella/vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js') }}"></script>
    <script src="{{ asset('gentelella/vendors/datatables.net-scroller/js/dataTables.scroller.min.js') }}"></script>
    <script src="{{ asset('gentelella/vendors/jszip/dist/jszip.min.js') }}"></script>
    <script src="{{ asset('gentelella/vendors/pdfmake/build/pdfmake.min.js') }}"></script>
    <script src="{{ asset('gentelella/vendors/pdfmake/build/vfs_fonts.js') }}"></script>

<script type="text/javascript" language="javascript" src="https://cdn.datatables.net/1.10.11/js/jquery.dataTables.min.js">            
    

    <!-- jQuery -->
    <script src="{{ asset('gentelella/vendors/jquery/dist/jquery.min.js') }}"></script>
    <!-- Bootstrap -->
    
    <script src="{{ asset('gentelella/vendors/bootstrap/dist/js/bootstrap.min.js') }}"></script> 
    <!-- FastClick -->
    <script src="{{ asset('gentelella/vendors/fastclick/lib/fastclick.js') }}"></script>
    <!-- NProgress -->
    <script src="{{ asset('gentelella/vendors/nprogress/nprogress.js') }}"></script>
    <!-- Chart.js -->
    <script src="{{ asset('gentelella/vendors/Chart.js/dist/Chart.min.js') }}"></script>
    <!-- gauge.js -->
    <script src="{{ asset('gentelella/vendors/gauge.js/dist/gauge.min.js') }}"></script>
    <!-- bootstrap-progressbar -->
    <script src="{{ asset('gentelella/vendors/bootstrap-progressbar/bootstrap-progressbar.min.js') }}"></script>
    <!-- iCheck -->
    <script src="{{ asset('gentelella/vendors/iCheck/icheck.min.js') }}"></script>
    <!-- Skycons -->
    <script src="{{ asset('gentelella/vendors/skycons/skycons.js') }}"></script>
    <!-- Flot -->
    <script src="{{ asset('gentelella/vendors/Flot/jquery.flot.js') }}"></script>
    <script src="{{ asset('gentelella/vendors/Flot/jquery.flot.pie.js') }}"></script>
    <script src="{{ asset('gentelella/vendors/Flot/jquery.flot.time.js') }}"></script>
    <script src="{{ asset('gentelella/vendors/Flot/jquery.flot.stack.js') }}"></script>
    <script src="{{ asset('gentelella/vendors/Flot/jquery.flot.resize.js') }}"></script>
    <!-- Flot plugins -->
    <script src="{{ asset('gentelella/vendors/flot.orderbars/js/jquery.flot.orderBars.js') }}"></script>
    <script src="{{ asset('gentelella/vendors/flot-spline/js/jquery.flot.spline.min.js') }}"></script>
    <script src="{{ asset('gentelella/vendors/flot.curvedlines/curvedLines.js') }}"></script>
    <!-- DateJS -->
    <script src="{{ asset('gentelella/vendors/DateJS/build/date.js') }}"></script>
    <!-- JQVMap -->
    <script src="{{ asset('gentelella/vendors/jqvmap/dist/jquery.vmap.js') }}"></script>
    <script src="{{ asset('gentelella/vendors/jqvmap/dist/maps/jquery.vmap.world.js') }}"></script>
    <script src="{{ asset('gentelella/vendors/jqvmap/examples/js/jquery.vmap.sampledata.js') }}"></script>
    <!-- bootstrap-daterangepicker -->
    <script src="{{ asset('gentelella/vendors/moment/min/moment.min.js') }}"></script>
    <script src="{{ asset('gentelella/vendors/bootstrap-daterangepicker/daterangepicker.js') }}"></script>

    <!-- Custom Theme Scripts -->
    <script src="{{ asset('gentelella/build/js/custom.js') }}"></script>

    
    @yield("script")
    
   
</body>
</html>